refactor: changed to typeorem
lizaBukia/dnck-back pull request #12
Opened 2024-07-10 16:21 UTC by Nikajighauri

2024-07-10 16:33 UTC, pailodze requested changes

2024-07-10 16:33 UTC, pailodze commented on src/users/entities/users.entity.ts
> +  password: string;
We need createdAt deletedAt udpatedAt

2024-07-10 16:33 UTC, pailodze commented on src/users/repositories/users.repository.ts
> +    return await this.usersRepository.delete(id);
softRemove

2024-07-10 16:33 UTC, pailodze commented on src/users/users.controller.ts
> +    return await this.usersService.findOne(+id);
Use Number() for casting nubmer

2024-07-11 10:04 UTC, beqagerliAni commented on src/users/entities/users.entity.ts
> +  password: string;
ok

2024-07-11 10:06 UTC, merged