feat/MZAD-61/Auth-Module
lizaBukia/dnck-back pull request #15
Opened 2024-07-23 16:17 UTC by beqagerliAni

2024-07-29 09:45 UTC, pailodze requested changes

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.constants.ts
> +  secret: 'dnck',
variable name should be camelCase

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.controller.ts
> +  @Post('login')
refomat this code add spaces this is not readable

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.controller.ts
> +  login(@Body() authDto: AuthDto): Promise<LoginInterface> {
You sure login and register has the same dtos?

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.service.ts
> +  constructor(
same here add spaces the code is not readable

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.service.ts
> +    const hashedpassword: string = await bcrypt.hash(password, salt);
variable name should be hashedPassword

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.service.ts
> +    const salt: string = await bcrypt.genSalt();
add spaces here also

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.service.ts
> +    const chekpassword: boolean = await bcrypt.compare(password, user.password);
name this variable isPasswordCorrect = user && await bcrypt.compare(password, user.password)

2024-07-29 09:45 UTC, pailodze commented on src/auth/auth.service.ts
> +        access_token: await this.jwtService.signAsync(payload, {
return accessToken not access_token

2024-07-29 09:45 UTC, pailodze commented on src/auth/enum/user.role.ts
> +export enum role {
name should be RoleEnum

2024-07-29 09:45 UTC, pailodze commented on src/auth/enum/user.role.ts
> +  admin = 'admin',
Enum keys should be PascalCase

2024-07-29 09:45 UTC, pailodze commented on src/auth/enum/user.role.ts
> +export enum role {
File name should be user-roles.enum.ts

2024-07-29 09:45 UTC, pailodze commented on src/auth/gurads/auth.guard.ts
> +interface JwtPayload {
extract this interface to its own file and name it JwtPayloadInterface

2024-07-29 09:45 UTC, pailodze commented on src/auth/gurads/auth.guard.ts
> +interface RoleMetadata {
same this name RoleMetadataInterface and extract to its own folder

2024-07-29 09:45 UTC, pailodze commented on src/auth/gurads/auth.guard.ts
> +      if (roles && roles.roles && roles.roles.length) {
const isRouteGuardedWithRoles = roles.length 
why do we need roles.roles.length?

2024-07-29 09:45 UTC, pailodze commented on src/auth/gurads/role.guard.ts
> +  constructor(private reflector: Reflector) {}
why do you need role.guard? you have written logic already in auth.guard

2024-07-29 09:45 UTC, pailodze commented on src/auth/interface/login.response.ts
> +  access_token: string;
it shoudl be accessToken

2024-07-29 09:45 UTC, pailodze commented on src/users/entities/users.entity.ts
> +  @Column({ default: 'user' })
take the default value from enum

2024-07-29 09:45 UTC, pailodze commented on src/users/repositories/users.repository.ts
>    }
add space hrere

2024-07-29 09:45 UTC, pailodze commented on src/users/users.controller.ts
> +  @Public()
why this is public?

2024-07-29 10:01 UTC, beqagerliAni commented on src/users/users.controller.ts
> +  @Public()
gavteste prosta

2024-07-30 17:08 UTC, pailodze requested changes

2024-07-30 17:08 UTC, pailodze commented on src/auth/auth.controller.ts
> +  register(@Body() authdto: AuthDto): Promise<User> {
argument name should be camel case

2024-07-30 17:08 UTC, pailodze commented on src/auth/auth.service.ts
> +    if (user && isPasswordCorrect) {
if(isPasswordCorrect)

2024-07-30 17:08 UTC, pailodze commented on src/auth/enum/user.role.ts
> +  ADMIN = 'ADMIN',
Admin = 'admin',
User = 'user'

2024-07-30 17:08 UTC, pailodze commented on src/auth/gurads/auth.guard.ts
> +      if (roles && roles.roles && isRouteGuardedWithRoles) {
if(isRouteGuardedWithRoles)

2024-07-30 17:08 UTC, pailodze commented on src/auth/interface/payload.response.ts
> +  verifyAsync: boolean;
why this is here?

2024-07-30 17:08 UTC, pailodze commented on src/auth/auth.service.ts
> +    if (user && isPasswordCorrect) {
you forgot this!

2024-07-30 17:33 UTC, pailodze requested changes

2024-07-30 17:33 UTC, pailodze commented on src/auth/enum/user.role.ts
> +  ADMIN = 'admin',
Admin
User

2024-07-30 17:45 UTC, merged